### ISSUE TITLE
Can't build x64 Solution config with FsXaml in an x64 app, and x64 library

### ISSUE THREAD

**Issue by marklam** [fsprojects/FsXaml#19]
If you create a Xaml app using FsXaml, referencing a separate library, and set their build configurations and flags to x64, then building the solution fails with these errors:
``parse error FS3053: error : The type provider constructor has thrown an exception: Could not load file or assembly 'Testx64Library, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. This assembly was compiled for a different processor.``

``FSC: warning FS3005: Referenced assembly '``...``\Projects\FsXamlx64Test\packages\FsXaml.Wpf.0.9.9\lib\net45\FsXaml.Wpf.TypeProvider.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found
``

**Comment by marklam** [comment]
Also a similar problem trying to reference a mixed-mode (C++/CLI) assembly.

**Comment by ReedCopsey** [comment]
@marklam I believe this has been fixed in 2.0. Please see  #33 and let me know if you still have issues.
