### ISSUE TITLE
Runtime exception using C# library schema def for XAMl namespace declaration

### ISSUE THREAD

**Issue by jphiggs** [fsprojects/FsXaml#20]
HI Reed,

I'm using a third party C# charting library to create a sample app with F#.  I get a runtime exception (at App.Root.Run() ) if I use the lib's schema definition from its AssemblyInfo, for the XAML namespace declaration .  However, if I separately declare 4 library namespaces with xmlns, the sample runs fine.  Are you aware of why this could occur?

**Comment by ReedCopsey** [comment]
From what I remember, using a schema definition only works if the assembly has already been loaded.  If you reference a type in your application's .fs file prior to calling App.Root, does it work?

**Comment by jphiggs** [comment]
Yes, it does - just by creating a new chart and disposing it before App().Root.Run(), the rest seems to work fine.  Thanks.

**Comment by ReedCopsey** [comment]
@jphiggs BTW - The issue is that the namespace definitions are only added to the XAML parsing for loaded assemblies.  You don't need to actually create a full chart - any use of any type within the assembly should get it to load (and then work).
