### ISSUE TITLE
Support using from FSI

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/FsXaml#21]
FsXaml supports only loading the XAML files from a resource. It would be good if we could just load directly a XAML file from the current directory so we could use it on FSI

**Comment by ReedCopsey** [comment]
It looks like this may happen in the next release.

Note that it still only really allows one run, unless you're using dialogs, as Application can only be created a single time in WPF per AppDomain, but if you use dialogs, @BillHally 's approach seems solid.

**Comment by ReedCopsey** [comment]
Supported as of 3.1.6 - https://www.nuget.org/packages/FsXaml.Wpf/
