### ISSUE TITLE
X64 Compilation fails with an error

### ISSUE THREAD

**Issue by rk540** [fsprojects/FsXaml#22]
When compiling against an X64 cpu architecture library fsXaml fails with the following error.

```xml
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="d"
        Title="MainWindow" Height="414" Width="535">
    <Grid x:Name="MainGrid">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="247*"/>
            <ColumnDefinition Width="0*"/>
            <ColumnDefinition Width="270*"/>
        </Grid.ColumnDefinitions>
        <StackPanel HorizontalAlignment="Left" Height="25" Margin="0,359,0,0" VerticalAlignment="Top" Width="527" Grid.ColumnSpan="3" Orientation="Horizontal">
            <Button Content="Order Send" x:Name="OrderSend" Width="191" Height="25" VerticalAlignment="Bottom"/>
            <Button Content="Order Update" x:Name="OrderUpdate" Width="194"/>
            <Button Content="Order Cancel" x:Name="OrderCancel" Width="141"/>
        </StackPanel>
        <DataGrid x:Name="OrderGrid" HorizontalAlignment="Left" VerticalAlignment="Top" RenderTransformOrigin="-3.7,-3.231" Grid.ColumnSpan="3" Height="164" Width="517">
            <DataGrid.Columns>
                <DataGridTextColumn Header="id" Binding="{Binding id}"/>
                <DataGridTextColumn Header="qty" Binding="{Binding qty}"/>
                <DataGridTextColumn Header="status" Binding="{Binding status}"/>
                <DataGridTextColumn Header="execqty" Binding="{Binding execqty}"/>
            </DataGrid.Columns>
        </DataGrid>
        <Label Content="Symbol" HorizontalAlignment="Left" Margin="0,169,0,0" VerticalAlignment="Top" Height="30" Width="58"/>
        <TextBox x:Name="Symbol" HorizontalAlignment="Left" Height="23" Margin="101,169,0,0" TextWrapping="Wrap"  VerticalAlignment="Top" Width="141"/> 
        <RadioButton x:Name="Buy" Content="Buy" HorizontalAlignment="Left" Margin="10,204,0,0" VerticalAlignment="Top" GroupName="buysell"/>
        <RadioButton x:Name="Sell" Content="Sell" HorizontalAlignment="Left" Margin="101,204,0,0" VerticalAlignment="Top" RenderTransformOrigin="0.296,0.312" GroupName="buysell"/>
        <Label Content="Quantity" Grid.Column="2" HorizontalAlignment="Left" Margin="7,169,0,0" VerticalAlignment="Top" RenderTransformOrigin="-1,0.5"/>
        <TextBox x:Name="Quantity" Grid.Column="2" HorizontalAlignment="Left" Height="23" Margin="84,169,0,0" TextWrapping="Wrap"  VerticalAlignment="Top" Width="181"/>
        <TextBox x:Name="Account" Grid.Column="2" HorizontalAlignment="Left" Height="23" Margin="84,204,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="181"/>
        <Label Content="Account" Grid.Column="2" HorizontalAlignment="Left" Margin="10,202,0,0" VerticalAlignment="Top" RenderTransformOrigin="0.553,-0.346" Width="53"/>
        <RadioButton x:Name="Market"  Content="Market" HorizontalAlignment="Left" Margin="10,243,0,0" VerticalAlignment="Top" GroupName="ordertype"/>
        <RadioButton x:Name="Limit" Content="Limit" HorizontalAlignment="Left" Margin="101,243,0,0" VerticalAlignment="Top" d:IsHidden="True" GroupName="ordertype"/>
        <Label Content="Price" Grid.Column="2" HorizontalAlignment="Left" Margin="10,241,0,0" VerticalAlignment="Top"/>
        <TextBox x:Name="Price" Grid.Column="2" HorizontalAlignment="Left" Height="23" Margin="84,243,0,0" TextWrapping="Wrap"  VerticalAlignment="Top" Width="181"/>
        <Label Content="XML Config" HorizontalAlignment="Left" Margin="0,273,0,0" VerticalAlignment="Top"/>
        <TextBox x:Name="Config" HorizontalAlignment="Left" Height="23" Margin="101,273,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="322" Grid.ColumnSpan="3"/>
        <Button x:Name="Init" Content="Init Fmwk" Grid.Column="2" HorizontalAlignment="Left" Margin="176,271,0,0" VerticalAlignment="Top" Width="89"/>
    </Grid>
</Window>
```

``` f#
open System
open System.Windows
open System.Windows.Controls
open FsXaml
open System.Xml
open System.Collections.Generic

type  Mainwindow = XAML<"gui.xaml">
[<STAThread>]
    try
        Application().Run( new Mainwindow() ) |> ignore

```
------ Build started: Project: atfgui, Configuration: Debug Any CPU
------
        C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe
-o:obj\Debug\atfgui.exe -g --debug:full --noframework --define:DEBUG
--define:TRACE --doc:bin\Debug\atfgui.XML --optimize- --tailcalls-
--platform:x64 -r:C:\Dev\ATF\assembly\Debug\frameworkevents.dll
-r:C:\Dev\ATF\tp\FsXaml\Debug\FsXaml.Wpf.dll
-r:C:\Dev\ATF\tp\FsXaml\Debug\FsXaml.Wpf.TypeProvider.dll
-r:C:\Dev\ATF\assembly\Debug\hostengine.dll
-r:C:\Dev\ATF\assembly\Debug\mktdataservices.dll
-r:C:\Dev\ATF\assembly\Debug\mktdatastructs.dll -r:"C:\Program Files
(x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll"
-r:C:\Dev\ATF\assembly\Debug\persistence.dll -r:"C:\Program Files
(x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.5\PresentationCore.dll"
-r:"C:\Program Files (x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.5\PresentationFramework.dll"
-r:"C:\Program Files (x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll"
-r:"C:\Program Files (x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll"
-r:"C:\Program Files (x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Numerics.dll"
-r:C:\Dev\ATF\framework\examples\atfgui\packages\Expression.Blend.Sdk.1.0.2\lib\net45\System.Windows.Interactivity.dll
-r:"C:\Program Files (x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xaml.dll"
-r:"C:\Program Files (x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll"
-r:C:\Dev\ATF\assembly\Debug\tradingclasses.dll -r:"C:\Program Files
(x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.5\WindowsBase.dll"
--target:exe --warn:3 --warnaserror:76 --vserrors
--validate-type-providers --LCID:1033 --utf8output --fullpaths
--flaterrors --subsystemversion:6.00 --highentropyva+
--sqmsessionguid:ed3396d7-c111-4f7c-91a2-bf3691c7001c
"c:\temp\.NETFramework,Version=v4.5.AssemblyAttributes.fs" atfgui.fs
FSC: error FS3031: The type provider
'C:\Dev\ATF\tp\FsXaml\Debug\FsXaml.Wpf.TypeProvider.dll' reported an
error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a
designer assembly 'FsXaml.Wpf.TypeProvider' which cannot be loaded or
doesn't exist. Could not load file or assembly
'file:///C:\Dev\ATF\tp\FsXaml\Debug\FsXaml.Wpf.TypeProvider.dll'; or
one of its dependencies. An attempt was made to load a program with an
incorrect format.
FSC: warning FS3005: Referenced assembly
'C:\Dev\ATF\tp\FsXaml\Debug\FsXaml.Wpf.TypeProvider.dll' has assembly
level attribute
'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute'
but no public type provider classes were found
Done building project "atfgui.fsproj" -- FAILED.

Build FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped
==========

**Comment by ReedCopsey** [comment]
I believe this has been fixed in the 2.0 release. See #33
