### ISSUE TITLE
.NET Universal?

### ISSUE THREAD

**Issue by saosebastiao** [fsprojects/FsXaml#23]
From [this comment thread](http://www.reddit.com/r/fsharp/comments/373j5v/net_universal_apps_and_f/crji1ey) , there is a mention of a desire to use FsXaml with .NET Universal apps, which I would echo. Is this difficult to support?

**Comment by ReedCopsey** [comment]
@saosebastiao It may be possible, but I don't know all of what would be involved at this point in time.  I personally don't have any need for this, so I haven't had a lot of time to investigate what would be involved.
