### ISSUE TITLE
UserControl Focusable

### ISSUE THREAD

**Issue by shawn-martin** [fsprojects/FsXaml#28]
UserControls created via the provider are focusable whereas normal UserControls are not.  This is not desired behavior in my current project so I've worked around it by adding a Blend behavior to each of my UserControls, but it would be nice if this wasn't necessary.  A little troubleshooting: the provided type for UserControls is inheriting from ContentControl which seems to default its Focusable property to true.  UserControl also inherits from ContentControl, but seems to default Focusable to false.

**Comment by ReedCopsey** [comment]
@shawn-martin Please see https://github.com/fsprojects/FsXaml/issues/29#issuecomment-218262194

The new version, once completed, should address this.  It eliminates the "container" types, so doing a `type MyControl = XAML<"MyControl.xaml">` creates something that is directly a user control (not a UC inside of a ContentControl).  Look for this soon.
