### ISSUE TITLE
An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in FsXaml.Wpf.dll

### ISSUE THREAD

**Issue by goldengrisha** [fsprojects/FsXaml#31]
Hello. Sorry for my question, but i can't figure out how it works, I need to load <ResourceDictionary Source="pack://application:,,,/App;component/Resources/Icons.xaml" /> (mahapp) and it gives me 
An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in FsXaml.Wpf.dll

**Comment by ReedCopsey** [comment]
You should be able to look at the inner exceptions of the XamlParseException in the debugger.  That should give you a clue as to why things aren't loading properly.

Unfortunately, XAML errors show up this way...

**Comment by ReedCopsey** [comment]
[Feel free to reopen if you feel that it's an FsXaml issue, or need more information...]

**Comment by goldengrisha** [comment]
Set property 'System.Windows.ResourceDictionary.Source' 
here is my dic:

<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Canvas x:Key="appbar_3d_3ds" x:Shared="False" Width="76" Height="76" Clip="F1 M 0,0L 76,0L 76,76L 0,76L 0,0">
        <Path Width="32" Height="40" Canvas.Left="23" Canvas.Top="18" Stretch="Fill" Fill="Black" Data="F1 M 27,18L 23,26L 33,30L 24,38L 33,46L 23,50L 27,58L 45,58L 55,38L 45,18L 27,18 Z "/>
    </Canvas>

    <Canvas x:Key="appbar_uservoice" x:Shared="False" Width="76" Height="76" Clip="F1 M 0,0L 76,0L 76,76L 0,76L 0,0">
        <Path Width="44.3333" Height="41.1667" Canvas.Left="14.25" Canvas.Top="17.4167" Stretch="Fill" Fill="Black" Data="F1 M 49.875,17.4167C 54.6845,17.4167 58.5833,25.9232 58.5833,36.4167C 58.5833,46.9101 54.6845,55.4167 49.875,55.4167C 48.1778,55.4167 46.594,54.3574 45.2549,52.5252C 42.2107,49.2413 39.0479,44.3333 34.8333,44.3333C 31.6667,44.3333 34.4375,47.5 34.4375,50.6667C 34.4375,53.8333 34.8333,58.5833 30.0833,58.5833C 25.3333,58.5833 20.5833,53.8333 22.1667,52.25C 23.75,50.6667 23.75,44.3333 23.75,44.3333C 19,44.3333 14.25,41.1667 14.25,36.4167C 14.25,31.6667 19,26.9167 31.6667,26.9167C 44.3333,26.9167 41.9583,17.4167 49.875,17.4167 Z M 41.1667,36.4167C 41.1667,31.7503 41.9377,27.4768 43.2169,24.1696C 40.8022,26.9173 42.75,28.5 31.8189,30.2356C 21.5881,30.2356 17.7516,32.8846 17.7516,36.7212C 17.7516,40.5577 21.984,41.5321 25.8205,41.5321C 25.8205,41.5321 27.008,50.6058 25.7292,51.8846C 24.4503,53.1635 25.9119,55.0208 29.7484,55.0208C 33.5849,55.0208 30.8902,50.3926 30.8902,47.8349C 30.8902,45.2772 30.0833,41.1667 34.3766,41.1362C 42.75,44.3333 39.9188,43.7895 42.4678,46.4124C 41.6429,43.5087 41.1667,40.084 41.1667,36.4167 Z M 50.6667,20.5833C 48.5363,20.5833 46.7335,25.2581 46.1312,31.698C 50.4667,31.9701 53.8333,33.9789 53.8333,36.4167C 53.8333,38.8544 50.4667,40.8632 46.1312,41.1353C 46.7335,47.5752 48.5363,52.25 50.6667,52.25C 53.29,52.25 55.4167,45.1612 55.4167,36.4167C 55.4167,27.6722 53.29,20.5833 50.6667,20.5833 Z M 49.0833,20.5833C 45.5855,20.5833 42.75,27.6722 42.75,36.4167C 42.75,45.1612 45.5855,52.25 49.0833,52.25L 49.5056,52.2154C 46.6172,51.6722 44.3333,44.8065 44.3333,36.4167C 44.3333,28.0269 46.6172,21.1611 49.5055,20.618L 49.0833,20.5833 Z "/>
    </Canvas>
    
    <Canvas x:Key="appbar_user_delete" x:Shared="False" Width="76" Height="76" Clip="F1 M 0,0L 76,0L 76,76L 0,76L 0,0">
        <Path Width="41.1667" Height="43.2467" Canvas.Left="15.8333" Canvas.Top="19" Stretch="Fill" Fill="Black" Data="F1 M 15.8333,47.6921L 19.1921,44.3333L 24.79,49.9312L 30.3879,44.3333L 33.7467,47.6921L 28.1488,53.29L 33.7467,58.8879L 30.3879,62.2467L 24.79,56.6488L 19.1921,62.2467L 15.8333,58.8879L 21.4313,53.29L 15.8333,47.6921 Z M 38,19C 43.5417,19 45.9167,22.1667 45.1174,28.8134C 45.8315,29.2229 46.3125,29.9928 46.3125,30.875C 46.3125,31.9545 45.5923,32.8658 44.6061,33.1546C 44.1941,34.623 43.5543,35.9229 42.75,36.9628L 42.75,41.9583C 45.3889,42.4861 47.5,42.75 50.6667,44.3333C 53.8333,45.9167 54.8889,47.3681 57,49.4792L 57,57L 35.0254,57L 31.3154,53.29L 36.9134,47.6921L 31.4387,42.3108L 33.25,41.9583L 33.25,36.9628C 32.4457,35.9229 31.8059,34.623 31.3939,33.1546C 30.4077,32.8658 29.6875,31.9545 29.6875,30.875C 29.6875,29.9928 30.1685,29.2229 30.8826,28.8134C 30.0833,22.1667 32.4583,19 38,19 Z M 25.3333,44.3333C 26.5732,43.7134 27.6513,43.2957 28.6626,42.9853L 24.8366,46.8112L 23.4419,45.4165L 25.3333,44.3333 Z "/>
    </Canvas>

    <Canvas x:Key="appbar_user_minus" x:Shared="False" Width="76" Height="76" Clip="F1 M 0,0L 76,0L 76,76L 0,76L 0,0">
        <Path Width="38" Height="38" Canvas.Left="19" Canvas.Top="19" Stretch="Fill" Fill="Black" Data="F1 M 19,45.9167L 39.5833,45.9167L 39.5833,50.6667L 19,50.6667L 19,45.9167 Z M 38,19C 43.5417,19 45.9167,22.1667 45.1174,28.8134C 45.8315,29.2229 46.3125,29.9928 46.3125,30.875C 46.3125,31.9545 45.5923,32.8658 44.6061,33.1546C 44.1941,34.623 43.5543,35.9229 42.75,36.9628L 42.75,41.9583C 45.3889,42.4861 47.5,42.75 50.6667,44.3333C 53.8333,45.9167 54.8889,47.3681 57,49.4792L 57,57L 19,57L 19,52.25L 41.1667,52.25L 41.1667,44.3333L 25.3333,44.3333C 28.5,42.75 30.6111,42.4861 33.25,41.9583L 33.25,36.9628C 32.4457,35.9229 31.8059,34.623 31.3939,33.1546C 30.4077,32.8658 29.6875,31.9545 29.6875,30.875C 29.6875,29.9928 30.1685,29.2229 30.8826,28.8134C 30.0833,22.1667 32.4583,19 38,19 Z "/>
    </Canvas>

    <Canvas x:Key="appbar_user_tie" x:Shared="False" Width="76" Height="76" Clip="F1 M 0,0L 76,0L 76,76L 0,76L 0,0">
        <Path Width="38" Height="38" Canvas.Left="19" Canvas.Top="19" Stretch="Fill" Fill="Black" Data="F1 M 38,19C 43.5417,19 45.9167,22.1667 45.1174,28.8134C 45.8315,29.2229 46.3125,29.9928 46.3125,30.875C 46.3125,31.9545 45.5923,32.8658 44.6061,33.1546C 44.1941,34.623 43.5543,35.9229 42.75,36.9628L 42.75,41.9583C 45.3889,42.4861 47.5,42.75 50.6667,44.3333C 53.8333,45.9167 54.8889,47.3681 57,49.4792L 57,57L 19,57L 19,49.4792C 21.1111,47.3681 22.1667,45.9167 25.3333,44.3333C 28.5,42.75 30.6111,42.4861 33.25,41.9583L 33.25,36.9628C 32.4457,35.9229 31.8059,34.623 31.3939,33.1546C 30.4077,32.8658 29.6875,31.9545 29.6875,30.875C 29.6875,29.9928 30.1685,29.2229 30.8826,28.8134C 30.0833,22.1667 32.4583,19 38,19 Z M 35.2292,44.3333L 36.8125,47.5L 39.1875,47.5L 40.7708,44.3333L 35.2292,44.3333 Z M 36.4167,49.0833L 38,55.4167L 39.5833,49.0833L 36.4167,49.0833 Z "/>
    </Canvas>

    <Canvas x:Key="appbar_user" x:Shared="False" Width="76" Height="76" Clip="F1 M 0,0L 76,0L 76,76L 0,76L 0,0">
        <Path Width="38" Height="38" Canvas.Left="19" Canvas.Top="19" Stretch="Fill" Fill="Black" Data="F1 M 38,19C 43.5417,19 45.9167,22.1667 45.1174,28.8134C 45.8315,29.2229 46.3125,29.9928 46.3125,30.875C 46.3125,31.9545 45.5923,32.8658 44.6061,33.1546C 44.1941,34.623 43.5543,35.9229 42.75,36.9628L 42.75,41.9583C 45.3889,42.4861 47.5,42.75 50.6667,44.3333C 53.8333,45.9167 54.8889,47.3681 57,49.4792L 57,57L 19,57L 19,49.4792C 21.1111,47.3681 22.1667,45.9167 25.3333,44.3333C 28.5,42.75 30.6111,42.4861 33.25,41.9583L 33.25,36.9628C 32.4457,35.9229 31.8059,34.623 31.3939,33.1546C 30.4077,32.8658 29.6875,31.9545 29.6875,30.875C 29.6875,29.9928 30.1685,29.2229 30.8826,28.8134C 30.0833,22.1667 32.4583,19 38,19 Z "/>
    </Canvas>
    
</ResourceDictionary>

**Comment by ReedCopsey** [comment]
You're not showing the entire code - it's difficult to know whether the problem is elsewhere or not...

Can you edit to show the full code of the file?

**Comment by goldengrisha** [comment]
Thank you for your answer, I found the problem in x:Shared attribute.

-

**Comment by ReedCopsey** [comment]
@goldengrisha Great - glad you got it working.
