### ISSUE TITLE
Can't build x64 Solution config with FsXaml in an x64 app, and x64 library (v2)

### ISSUE THREAD

**Issue by marklam** [fsprojects/FsXaml#34]
### Description

If you create a Xaml app using FsXaml, referencing a separate library, and set their build configurations and flags to x64, then building the solution fails with this error:
``parse error FS3053: error : The type provider constructor has thrown an exception: Could not load file or assembly 'Testx64Library, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. This assembly was compiled for a different processor.``

### Repro steps

Build the x64 configuration of the project at https://github.com/marklam/bugrepro-fsxaml-19
This includes a ViewModel assembly set to x64, and an app set to x64

### Expected behavior

A working (but empty) app, as seen when building 'Any CPU'

### Actual behavior

``parse error FS3053: error : The type provider constructor has thrown an exception: Could not load file or assembly 'Testx64Library, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. This assembly was compiled for a different processor.``

**Comment by ReedCopsey** [comment]
@marklam I believe this will now be fixed in Beta 3: https://www.nuget.org/packages/FsXaml.Wpf/2.0.0-beta3

Please test and let me know if it works for you.  It works in my testing.

**Comment by marklam** [comment]
Yes, that's working for me. Thanks!

**Comment by ReedCopsey** [comment]
Glad to hear it!
