### ISSUE TITLE
Add ProjectScaffold documentation generators

### ISSUE THREAD

**Issue by ReedCopsey** [fsprojects/FsXaml#39]
Which would allow us to write "real" docs for FsXaml.

It would be nice to build this in...

**Comment by jschiefer** [comment]
As part of the nuget->Paket migration, I was planning to update the build.fsx and associated bits and pieces to the current versions in ProjectScaffold (to pick up the right build magic for Paket). Is that all that would be needed, or is there more?

**Comment by ReedCopsey** [comment]
Not sure, to be honest.  Paket is easy... could just do the update from
nuget on the demos project.  Getting missing buts of scaffolding would be a
bigger job, I think

**Comment by ReedCopsey** [comment]
Thanks to @jschiefer , this is now complete.

http://fsprojects.github.io/FsXaml/

Initial pages scaffolded and online - will work on better documentation now.
