### ISSUE TITLE
Get editor warning but runtime is fine

### ISSUE THREAD

**Issue by lijunle** [fsprojects/FsXaml#41]
### Description

See the picture:

![image](https://cloud.githubusercontent.com/assets/1296500/15371400/cd6376ae-1d6d-11e6-8b37-82f9a1802183.png)

(I am using the newest 2.0.0, but it is report 0.9.9. I have no idea about this.)

However, Hit F5, everything is working fine.

### Repro steps

1. Setup a F# project,
2. Install FsXaml 2.0 from Nuget
3. Write some XAML and its corresponding .xaml.fs files.

### Expected behavior

I should get type intellisense from VS.

### Actual behavior

VS is complaining some error, no type intellisense. :disappointed: 

### Known workarounds

No idea.

### Related information 

* Operating system: Windows 10
* Branch: The version 2.0.0 from NuGet.
* .NET Runtime, CoreCLR or Mono Version: 4.5.2
* Performance information, links to performance testing scripts: N/A

**Comment by ReedCopsey** [comment]
This is coming from F# Power Tools. If you upgrade to the latest F# Power Tools, this will go away.

**Comment by lijunle** [comment]
@ReedCopsey After upgrade the F# Power Tools, the warning is gone. Thanks for your awesome tools! :smile_cat:
