### ISSUE TITLE
Error from TypeProvider

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/FsXaml#44]
I got this error:
```
Could not load type 'FsXaml.XamlContainer' from assembly 'FsXaml.Wpf, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

I used the `yo fsharp` generator to start my project as a standalone project.

**Comment by ReedCopsey** [comment]
I'd make sure you're using the latest version (*2.1) of FsXaml.  It sounds like you're using the older versions, but using new tooling (ie: FS Power Tools), which can cause erroneous errors to occur within VS.

Please see if upgrading to the latest nuget solves the issue.

**Comment by MangelMaxime** [comment]
Hum yes you are right I was using an old version.

I got another error on runtime but will try to figure it out with the samples :).

Tanks again.
