### ISSUE TITLE
Input String was not in correct format

### ISSUE THREAD

**Issue by fjoppe** [fsprojects/FsXaml#46]
### Description

"Input String was not in correct format" when creating a new project with FsXaml template.
### Repro steps
1. Searched for "FsXaml" via template selection and installed it, checked it via "Extensions and updates";
2. New Project, choose "F# Empty Windows App (WPF)";
3. Change folder and filename;
4. Click "OK".
### Expected behavior

Creates new, empty F# WPF project
### Actual behavior

Creates the solution folder and sub-folder, but does not create any files. Displays alert message "Input String was not in correct format".
## 
### Related information
- OS: Windows 10
- .NET Runtime: Selected 4.5.2
- Visual Studio 2015 Community Edition, v14.0.25424.00 Update 3

**Comment by ReedCopsey** [comment]
That template isn't actually associated with FsXaml, or part of this project.  I will see whether it can be updated to use the current versions of FsXaml so it works properly.

**Comment by fjoppe** [comment]
Ok thanks. I think it is [this](https://visualstudiogallery.msdn.microsoft.com/e0907c99-bb04-4eb8-9692-9333d5ff4399) template. The tool-names are a bit alike, so there's my confusion.

**Comment by ReedCopsey** [comment]
@fjoppe Thanks - I believe it's https://github.com/fsprojects/FSharpCommunityTemplates/blob/master/VisualStudio/FSharpWpfEmptyTemplate/VSIX/ProjectTemplates/WPF/FSharpWpfEmpty.zip   I'll see about trying to update it.

**Comment by ReedCopsey** [comment]
I think we'll address this as part of #63 instead of trying to get the community templates updated.  This will allow us to iterate them with new versions more easily.

**Comment by octopusgrabbus** [comment]
Reed: I am having this issue with Visual Studio 2015. Can you point me to a workaround? If not, when do you expect the template to be fixed? Thanks.

**Comment by ReedCopsey** [comment]
@octopusgrabbus I'd recommend not using the template - @Lleutch is working on a new set of templates (see #63), but there is no time frame for when that'll be finished.

The templates referenced in this issue are not ones written by us, so it's difficult for us to get them corrected.  If you use them, you'll just need to update the nuget references to the latest FsXaml, then remove the `, true` in the XAML calls, and it should work.  That being said, I don't recommend the templates in general - they aren't ideal, and they don't add much, as there is little needed w.r.t. a template for using FsXaml.

**Comment by octopusgrabbus** [comment]
Thanks @ReedCopsey Your answer was helpful.
