### ISSUE TITLE
XAML fails to load at run-time if it's in a sub-folder

### ISSUE THREAD

**Issue by brianberns** [fsprojects/FsXaml#57]
If the target XAML file is located in a sub-folder, it can be accessed at compile-time, but not at run-time.

`type MyView = FsXaml.XAML<"Views\MyView.xaml">`

Error message: _The specified resource name "views\myview.xaml" does not exist in the resource file._

**Comment by ReedCopsey** [comment]
@brianberns What happens if you use `"Views/MyView.xaml"` instead?

**Comment by brianberns** [comment]
That works! Thanks.
