### ISSUE TITLE
Change to MIT License

### ISSUE THREAD

**Issue by ReedCopsey** [fsprojects/FsXaml#59]
I'd like to change this project from Apache to MIT licensing, in order to be the least restrictive possible.

I've tried to go through the commit list, and checked for all contributors who have contributed code to the project itself, which still exists in some form or another.  

Would you all please comment here that you either agree, or let me know why you object, so we can re-license this in a future release?

Thank you,
Reed

People who have contributed code which still exists in some form:
- [x] @reedcopsey
- [x] @kevlut 
- [x] @JohanLarsson 
- [x] @jschiefer 
- [x] @vasily-kirichenko

**Comment by kevlut** [comment]
For the people! I'm in

**Comment by jschiefer** [comment]
Fine with me also.

**Comment by vasily-kirichenko** [comment]
I agree, great move.

**Comment by JohanLarsson** [comment]
Fine with me.

**Comment by ReedCopsey** [comment]
Changed for 3.1.2.  Thanks all!
