### ISSUE TITLE
Error in XAML type provider : Could not load type ...

### ISSUE THREAD

**Issue by Ummon** [fsprojects/FsXaml#60]
### Description

I upgraded FsXaml.Wpf from 2.2.0 to 3.1.1 and this error happened:

![fsxaml_error](https://cloud.githubusercontent.com/assets/89829/22583346/3e8613aa-e9ec-11e6-97ab-5a9904cb6765.png)

I used NuGet package manager in Visual Studio and just clicked 'Update'.

### Related information 

* Operating system: Windows 7
* IDE: Visual Studio 2015 pro
* .NET: 4.61 and F# runtime 4.4.0.0

**Comment by ReedCopsey** [comment]
@Ummon This is a "false error" that happens only if F# Power Tools is enabled.  It'll go away once I get them to update their internal version of fsxaml.  I'm fixing one other FsXaml bug, but will then put a PR into that project to resolve.

For now, everything builds fine.  You can ignore this error or temporarily disable f#pt.

**Comment by ReedCopsey** [comment]
I've put the pull request in - https://github.com/fsprojects/VisualFSharpPowerTools/pull/1495 

A compatible build should show up in the artifacts of the AppVeyor build on that PR.

**Comment by ReedCopsey** [comment]
Feel free to download new version from https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.5.6-a1702031943/artifacts if you don't want to wait for an official release...

**Comment by ReedCopsey** [comment]
Can be downloaded prior to official release from https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.5.6-a1702031951/artifacts

**Comment by Ummon** [comment]
Thanks for you answer. I tried to upgrade F# Power tools to the linked version you re-tried the FsXaml.Wpf 3.1.2 version but I still have this error (first error during compilation):

~~~
ActionsPartView.xaml.fs(10,28): error FS3033: The type provider 'FsXaml.XamlTypeProvider' reported an error: Object reference not set to an instance of an object.
~~~

Live compilation give me the same error:

![fsxaml_error_2](https://cloud.githubusercontent.com/assets/89829/22687984/8e260578-ed2a-11e6-853d-75d4aba1fe0c.png)

**Comment by ReedCopsey** [comment]
I'm guessing  this is a separate, unrelated issue.  Any chance you can make
a small Repro, and I can take a look?
