### ISSUE TITLE
Sign FsXaml.Wpf assembly

### ISSUE THREAD

**Issue by kirill-gerasimenko** [fsprojects/FsXaml#62]
Hi,
Thanks for the awesome library!

### Description
Unable to load FsXaml.Wpf assembly from signed VSIX project.

This is the message from the original exception:
"Could not load file or assembly 'FsXaml.Wpf, Version=3.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)" 

### Known workarounds
Do not sign VSIX project. In this case everything works fine, exception is gone. 

Would it be possible to sign the assembly?

--
Kirill

**Comment by ReedCopsey** [comment]
I'll put out an update, and sign it, this week.  Seems perfectly
reasonable.

Out of curiosity, what vsix are you producing using FsXaml?

**Comment by kirill-gerasimenko** [comment]
Great, thanks!

I'm just experimenting and needed to have some UI in the vsix add on so FsXaml seems reasonable. 

------------
Kirill

**Comment by ReedCopsey** [comment]
This has now been done, and released in 3.1.3 https://www.nuget.org/packages/FsXaml.Wpf/
