### ISSUE TITLE
VS 2017 message box when opening XAML file: Visual Studio has encountered an unexpected error.

### ISSUE THREAD

**Issue by BentTranberg** [fsprojects/FsXaml#68]
When I try to open a XAML file in VS 2017 on this particular machine, it won't open. If I double click the file in Solution Explorer, nothing at all happens. If I left-click and select Open, then this dialog box appears with the message "Visual Studio has encountered an unexpected error.", and that's all.

It happens with any XAML file in any project, and it only happens on this one machine. For this reason I don't see much use in supplying a repro, but I'll do that on request. I have another machine with what should be exactly the same setup, and there's no problem there. I also have other machines, and there's no problem with them either.

I am quite certain it used to work several weeks back, and I think the problem occurred now and then for some weeks, and now it's not possible at all to open XAML files.

Is this a problem with FsXaml, VS, F#, or ... ?

I do anticipate a reinstall of something will fix the problem, but first I'd rather contribute to fixing the bug if possible. With so little to go on, and the problem only on this machine, maybe I should just ignore and reinstall.

### Known workarounds

I have to use VS 2015 or another machine to edit XAML.

### Related information

FsXaml.Wpf 3.1.6 and 3.1.2
.NET Framework 4.5.2
Visual Studio 2017, v 15.2 (26430.14)
F# 4.0 (4.4.0.0)
F# Nightly builds 15.4.1.17062201
Windows 10

**Comment by ReedCopsey** [comment]
@BentTranberg From what you're describing, I think this _has_ to be a VS issue, not FsXaml. FsXaml doesn't interact with Visual Studio's editor in any manner whatsoever - it's only being used by the compiler and F# compiler services. I would suspect a VS extension, or some local corruption occurred, which is interfering with the XAML editor.
