### ISSUE TITLE
Can this be used with Xamarin.Forms?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FsXaml#70]
Can FsXaml be used with Xamarin.Forms XAML files (in PCLs or .NET Standard libraries)?

**Comment by ReedCopsey** [comment]
Unfortunately no. Xamarin Forms doesn't expose some of the required information I'd need to recreate this.

I hope to have some option there, but for now, manual loading (which is fairly simple) is the only option.

**Comment by cmeeren** [comment]
Yep, `LoadFromXaml` works fine, but all the `FindByName` calls are a pain... :) Thanks anyway!

**Comment by ReedCopsey** [comment]
Yeah. I've tried more than once. Most of the info required to figure out
the types is buried in internal routines in Xam Forms. Can't get to them.
Could easily do it untyped, but that's no better than calling findbyname
repeatedly.
