### ISSUE TITLE
XAML in sub folder doesn't load

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/FsXaml#76]
### Description

Perhaps related to #57. A XAML file in a sub-folder compiles, but then fails at runtime with the error

`'Unable to load XAML data. Verify that all .xaml files are compiled as "Resource"'`

### Repro steps

1. Clone the **wpf-sample** solution [here](https://github.com/isaacabraham/wpf-sample/commit/711e0e01eb6de5d911c544eda7a0e40cf588ba32).
2. Compile and run the solution (I used VS2017).

### Expected behavior

The application runs.

### Actual behavior

The application fails with a runtime error.

### Known workarounds

Don't use folders.

**Comment by FoggyFinder** [comment]
Works fine for me (VS2017[15.5.7])

**Comment by isaacabraham** [comment]
@FoggyFinder are you in the folders branch?

**Comment by isaacabraham** [comment]
@FoggyFinder ok. I've just cleaned the entire repository and rebuilt from scratch. It works now - don't know why. Maybe something was left in the obj folder or something from earlier. Sorry about that.
